// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleContent: typeof import('./src/components/ArticleContent.vue')['default']
    AudioComment: typeof import('./src/components/AudioComment.vue')['default']
    AudioDetail: typeof import('./src/components/AudioDetail.vue')['default']
    AudioIntroduction: typeof import('./src/components/AudioIntroduction.vue')['default']
    AudioPlay: typeof import('./src/components/AudioPlay.vue')['default']
    AudioProgram: typeof import('./src/components/AudioProgram.vue')['default']
    AudioSeriesView: typeof import('./src/components/AudioSeriesView.vue')['default']
    BoutiqueArea: typeof import('./src/components/BoutiqueArea.vue')['default']
    NewsWeek: typeof import('./src/components/NewsWeek.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextRun: typeof import('./src/components/TextRun.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanPopup: typeof import('vant/es')['Popup']
    VanSearch: typeof import('vant/es')['Search']
    VanSlider: typeof import('vant/es')['Slider']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
